apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-gnb-config
  namespace: free5gc
data:
  gnb.yaml: |
    mcc: '208'
    mnc: '93'
    nci: '0x000000010'
    idLength: 32
    tac: 1
    linkIp: 0.0.0.0
    ngapIp: 0.0.0.0
    gtpIp: 0.0.0.0
    amfConfigs:
      - address: 10.244.0.216
        port: 38412
    slices:
      - sst: 1
        sd: 0x010203
    ignoreStreamIds: true
