apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pdu-session-monitor
  namespace: free5gc
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: pdu-session-exporter
  endpoints:
  - port: metrics
    interval: 15s
